
import React, { createContext, useContext, useState, ReactNode } from "react";

// Define our translations
export const translations = {
  bg: {
    // Header
    features: "Функции",
    howItWorks: "Как работи",
    testimonials: "Отзиви",
    faq: "FAQ",
    
    // Hero
    heroTitle: "Кажи сбогом на хаоса при футболните срещи!",
    heroSubtitle: "Управлявай събития, играчи и плащания – директно от телефона си.",
    
    // Instructions
    instructions: "Инструкции",
    
    // Newsletter
    newsletterTitle: "Абонирай се за новини и функции",
    newsletterSubtitle: "Бъдете първите, които научават за нови функции, събития и съвети за организиране на мачове.",
    newsletterPlaceholder: "Вашият имейл",
    newsletterButton: "Абонирай се",
    newsletterDisclaimer: "Никога няма да споделяме вашия имейл. Можете да се отпишете по всяко време.",
    
    // Footer
    home: "Начало",
    support: "Поддръжка",
    help: "Помощ",
    contact: "Контакт",
    legal: "Правни",
    terms: "Условия за ползване",
    privacy: "Политика за поверителност",
    language: "Език",
    allRightsReserved: "Всички права запазени.",

    // Features
    featuresTitle: "Функции, които правят разликата",
    featuresSubtitle: "SureGo съдържа всичко, от което се нуждаете за безпроблемна организация на футболни събития",
    feature1Title: "Създаване на мачове и тренировки",
    feature1Desc: "Бързо планиране и управление на футболни събития с всички необходими детайли.",
    feature2Title: "Управление на играчи с роли и позиции",
    feature2Desc: "Организирайте играчите по позиции, умения и специални роли в отбора.",
    feature3Title: "Автоматични покани и известия",
    feature3Desc: "Автоматично изпращане на покани и напомняния към играчите за предстоящи мачове.",
    feature4Title: "Балансиране на отбори",
    feature4Desc: "Интелигентно разпределение на играчи за балансирани и конкурентни отбори.",
    feature5Title: "Проследяване на каса и плащания",
    feature5Desc: "Лесно проследяване на внесените суми и общия баланс на отбора.",
    feature6Title: "Игрова статистика и история",
    feature6Desc: "Преглед на статистики за мачове, посещаемост и представяне на отбора.",

    // How It Works
    howItWorksTitle: "Как работи SureGo?",
    howItWorksSubtitle: "Само шест лесни стъпки ви делят от перфектно организираните футболни събития",
    step1Title: "Свали приложението",
    step1Desc: "Изтеглете SureGo от App Store или Google Play безплатно.",
    step2Title: "Създай профил",
    step2Desc: "Бързо регистриране с Google, Apple ID или имейл.",
    step3Title: "Направи отбор",
    step3Desc: "Създайте своя отбор и настройте основните му параметри.",
    step4Title: "Добави играчи",
    step4Desc: "Поканете играчи с телефон или SureGo ID към вашия отбор.",
    step5Title: "Организирай събитие",
    step5Desc: "Задайте дата, час, локация и условия за участие.",
    step6Title: "Следи потвърждения и плащания",
    step6Desc: "Наблюдавайте кой е потвърдил и платил за участие.",

    // Registration
    registrationTitle: "Създаване на профил",
    regStep1Title: "Изтеглете приложението",
    regStep1Desc: "Достъпно в App Store и Google Play",
    regStep2Title: "Изберете начин за регистрация",
    regStep2Desc: "Няколко лесни начина за създаване на профил",
    regStep3Title: "Регистрация с имейл",
    regStep3Desc: "Въведете вашите данни за бърза регистрация",
    regStep4Title: "Активирайте профила си",
    regStep4Desc: "Потвърдете и започнете да използвате приложението",

    // App Showcase
    appShowcaseTitle: "Вижте приложението в действие",
    screenshot1Title: "Създай Отбор",
    screenshot2Title: "Покани Играчи",
    screenshot3Title: "Разпредели Играчите",
    screenshot4Title: "Организирай и Играй!",

    // Testimonials
    testimonialsTitle: "Доказани резултати",
    testimonialsSubtitle: "Хиляди организатори и футболисти вече разчитат на SureGo",
    testimonial1: "\"Най-сетне спряха оправданията – всеки знае кога и къде сме!\"",
    testimonial1Author: "Калоян",
    testimonial1Position: "организатор на мачове в София",
    testimonial2: "\"С SureGo организирането на мачове стана лесно! Вече нямаме проблеми с комуникацията.\"",
    testimonial2Author: "Мартин",
    testimonial2Position: "капитан на отбор във Варна",
    eventsOrganized: "организирани събития",
    activeTeams: "активни отбора",

    // FAQ
    faqTitle: "Често задавани въпроси",
    faqSubtitle: "Отговори на най-често задаваните въпроси за използването на SureGo",
    faq1Question: "Как се добавят играчи?",
    faq1Answer: "Можете да добавяте играчи по няколко начина: чрез изпращане на покана по имейл или телефон, споделяне на код за присъединяване или търсене по SureGo ID. След като играч приеме поканата, той автоматично се добавя към вашия отбор.",
    faq2Question: "Мога ли да променям състави?",
    faq2Answer: "Да, можете лесно да променяте съставите по всяко време. Просто отидете в секцията за управление на събития, изберете мача и преместете играчите между отборите. Системата също предлага автоматично балансиране на отборите според зададените умения на играчите.",
    faq3Question: "Как се следят плащанията?",
    faq3Answer: "SureGo предлага вградена система за проследяване на плащания. Можете да маркирате кой е платил, да изпращате напомняния за неплатени такси и да преглеждате общия баланс на отбора. Играчите получават автоматични известия за дължими суми и могат да маркират плащанията си през приложението.",
    faq4Question: "Работи ли за турнири?",
    faq4Answer: "Да, SureGo поддържа организиране на турнири с множество отбори. Можете да създадете турнирна структура, да следите резултати, да генерирате автоматично графици и да управлявате класирания. Функционалността за турнири е налична в разширения план на приложението.",

    // Call to Action
    ctaTitle: "Готов ли си да играеш без главоболия?",
    ctaSubtitle: "Свали SureGo сега и започни да организираш футболни събития лесно и бързо.",
    downloadApp: "Свали SureGo",

    // Instructions Page Translations
    instructionTitle1: "Създаване на профил в SureGo – бързо и лесно!",
    instructionDownloadApp: "Свалете приложението",
    instructionAvailableIn: "Достъпно е в:",
    instructionChooseRegistration: "Изберете начин за регистрация",
    instructionCanRegisterWith: "Можете да се регистрирате чрез:",
    instructionGoogleAccount: "Google акаунт",
    instructionAppleId: "Apple ID",
    instructionEmailRegistration: "Имейл (изберете \"Създай профил\")",
    instructionEmailRegTitle: "Ако сте избрали имейл регистрация:",
    instructionEnterEmail: "Въведете вашия имейл и парола",
    instructionPressCreateProfile: "Натиснете \"Създай профил\"",
    instructionCheckEmail: "Проверете имейла си за потвърждаващ линк",
    instructionActivateProfile: "Активирайте профила си",
    instructionOpenEmail: "Отворете имейла и кликнете върху линка за потвърждение",
    instructionReturnToApp: "Върнете се в приложението и изберете \"Вход с имейл\"",
    instructionEnterCredentials: "Въведете имейл и парола – и готово!",
    instructionProfileReady: "Вече имате активен профил и сте готови да започнете да използвате SureGo!",

    instructionTitle2: "Създайте своя отбор",
    instructionOpenSection: "Отворете раздела",
    instructionOpenTeamsSection: "Отворете раздела \"Отбори\"",
    instructionPressPlus: "Натиснете \"+\"",
    instructionPressPlusButton: "Натиснете \"+\" (в горния десен ъгъл)",
    instructionFillData: "Попълнете данни",
    instructionFillTeamData: "Попълнете име, държава, град и добавете снимка",
    instructionSave: "Запазете",
    instructionPressSave: "Натиснете \"Запази\" – и готово!",
    instructionTeamReady: "Вече сте готови да организирате мачовете си без главоболия!",

    instructionTitle3: "Добавяне и настройка на играчи в отбора",
    instructionTeamSubtitle: "Вече имате създаден отбор - нека го организираме перфектно!",
    instructionAccessPlayers: "Достъп до секцията за играчи:",
    instructionOpenTeams: "Отворете раздела \"Отбори\"",
    instructionSelectTeam: "Изберете вашия отбор",
    instructionClickPlayers: "Кликнете върху \"Играчи\"",
    instructionAddNewPlayer: "Добавяне на нов играч:",
    instructionChooseMethod: "Изберете удобен за вас метод:",
    instructionViaSureGoId: "Чрез SureGo ID (намерете го в профила на играча)",
    instructionViaPhone: "Чрез телефонен номер (ръчно въвеждане)",
    instructionViaContacts: "От контактите на телефона (автоматично свързване)",
    instructionPlayerConfig: "Конфигуриране на играча",
    instructionSetRole: "Задаване на роля:",
    instructionMainPlayer: "Основен",
    instructionMainPlayerDesc: "(приоритетни покани)",
    instructionReservePlayer: "Резервен",
    instructionReservePlayerDesc: "(поканват се втори)",
    instructionGuestPlayer: "Гост",
    instructionGuestPlayerDesc: "(поканват се при нужда)",
    instructionObserver: "Наблюдател",
    instructionObserverDesc: "(само преглед)",
    instructionSpecialty: "Специалност (позиция):",
    instructionGoalkeeper: "Вратар",
    instructionDefender: "Защитник",
    instructionMidfielder: "Полузащитник",
    instructionAttacker: "Нападател",
    instructionPositionsUsedFor: "Позициите се използват за:",
    instructionAutoBalance: "Автоматично балансиране на отборите при мачове",
    instructionDetailedStats: "Детайлна статистика по пост",
    instructionFormationAnalysis: "Анализ на използваните формации",
    instructionPlayerNotInSureGo: "Ако играчът все още не е в SureGo:",
    instructionSendInvite: "Можете да му изпратите инвайт линк по SMS, имейл или месинджър – той ще получи директна връзка за изтегляне на приложението и регистрация.",
    instructionAdditionalFeatures: "Допълнителни възможности:",
    instructionEditProfiles: "Редактиране на профили по-късно",
    instructionChangePositions: "Промяна на позиции и роли",
    instructionIndividualStats: "Индивидуална статистика за всеки играч",
    instructionAfterConfig: "След като конфигурирате играчите, ще можете:",
    instructionAutoSuggestions: "Да получавате автоматични предложения за оптимални състави",
    instructionTrackPerformance: "Да следите производителността по позиции",
    instructionAnalyzeStrengths: "Да анализирате силните и слабите страни на отбора",
    instructionFinalMessage1: "Приложението ще ви помогне да управлявате отбора професионално, като ви предоставя всички необходими инструменти за успех! ⚽📊",

    instructionTitle4: "Създаване на футболно събитие в SureGo",
    instructionEventSubtitle: "Организирайте перфектни мачове с няколко лесни стъпки!",
    instructionStartNewEvent: "Стартиране на ново събитие:",
    instructionSelectEvents: "От екрана на отбора изберете \"Събития\"",
    instructionBasicInfo: "Основна информация:",
    instructionEnterEventInfo: "Въведете име и описание на събитието",
    instructionAddLocation: "Добавете място (с възможност за точна локация чрез \"Карта\" бутон)",
    instructionPressNext: "Натиснете \"Напред\"",
    instructionMatchSettings: "Настройки на мача:",
    instructionDateTime: "Дата и време:",
    instructionSelectDate: "Изберете дата и начален час",
    instructionSetDuration: "Задайте продължителност (в минути)",
    instructionRepeatability: "Повторяемост:",
    instructionOneTime: "Еднократно",
    instructionOneTimeDesc: "(само за този ден)",
    instructionWeekly: "Ежеседмично",
    instructionWeeklyDesc: "(автоматично повторение)",
    instructionTeamCount: "Брой отбори:",
    instructionOneTeam: "1 отбор",
    instructionOneTeamDesc: "(игра срещу външен отбор)",
    instructionTwoTeams: "2 отбора",
    instructionTwoTeamsDesc: "(вътрешен мач)",
    instructionPlayers: "Играчи:",
    instructionSetMinPlayers: "Задайте минимален брой играчи",
    instructionPlayerInvites: "Покани за играчи:",
    instructionTimeIntervals: "Времеви интервали за покани:",
    instructionMainPlayers: "Основни играчи",
    instructionMainPlayersDesc: "(първи получават покана)",
    instructionReservePlayers: "Резерви",
    instructionReservePlayersDesc: "(получават след основните)",
    instructionGuestPlayers: "Гости",
    instructionGuestPlayersDesc: "(получават последни)",
    instructionDeadline: "Краен срок за потвърждение:",
    instructionDeadlineDesc: "Ако не се събере достатъчно играчи до този момент, събитието се отменя автоматично",
    instructionFinanceAndAdditional: "Финанси и допълнения:",
    instructionParticipationPrice: "Цена за участие:",
    instructionRoundingOption: "Възможност за закръгляване на сумата (остатъкът отива в хазната)",
    instructionFreeOption: "Безплатен вариант (ако желаете)",
    instructionFinalization: "Финализиране:",
    instructionAddNotes: "Добавете бележки (по избор)",
    instructionCompleteWithCreate: "Завършете с \"Създай събитие\"",
    instructionEventReady: "Готово!",
    instructionEventActive: "Събитието е активно и поканите са изпратени според зададените настройки.",
    instructionAdditionalPossibilities: "Допълнителни възможности:",
    instructionAutoTeamBalance: "Автоматично балансиране на отборите (ако е вътрешен мач)",
    instructionTrackConfirmations: "Проследяване на потвърждения в реално време",
    instructionEventNotifications: "Известия за промени по събитието",
    instructionAutoFillPlayers: "Опция за автоматично попълване на липсващи играчи от резервете",
    instructionFinalMessage2: "Приложението ще ви уведоми за всяка промяна в статуса на събитието и ще ви помогне да организирате перфектен мач без главоболия! ⚽📅",

    instructionTitle5: "Управление на плащанията за събитие",
    instructionPaymentSubtitle: "Ефективно и прозрачно управление на финансите за всяко събитие!",
    instructionPaymentProcess: "Процес на регистрация на плащания:",
    instructionOpenEvent: "Отворете желаното събитие като го изберете от предстоящи или минали",
    instructionPressDollarButton: "Натиснете бутона \"$\" в горния десен ъгъл",
    instructionPaymentScreen: "Екран за управление на плащания:",
    instructionSeeParticipants: "Виждате списък с всички участници",
    instructionSeeAmount: "В горната част се показва сумата за плащане (която може да се редактира)",
    instructionForEachPlayer: "За всеки играч имате възможност да:",
    instructionAddExtraAmount: "Добавите допълнителна сума (остава в портфейла на играча за бъдещи събития)",
    instructionReduceAmount: "Намалите сумата",
    instructionProcessCompletion: "Завършване на процеса:",
    instructionPressRedButton: "Натиснете червения бутон в горния десен ъгъл",
    instructionSeeSummary: "Ще видите обобщение с:",
    instructionEventPrice: "Цената на събитието",
    instructionTotalCollected: "Общо събрана сума",
    instructionTeamTreasury: "Сума за хазната на отбора",
    instructionConfirmYes: "Потвърдете с \"Да\"",
    instructionAdditionalInfo: "Допълнителна информация:",
    instructionUnpaidPlayers: "Ако има играчи, които не са платили, системата проверява:",
    instructionTreasuryCheck: "Дали хазната на отбора може да покрие липсващата сума",
    instructionInsufficientFunds: "Ако няма достатъчно средства, процесът не може да бъде завършен",
    instructionSystemAdvantages: "Предимства на системата:",
    instructionConvenientManagement: "Удобно управление на плащанията без необходимост от връщане на ресто",
    instructionFullTransparency: "Пълна финансова прозрачност",
    instructionAutoCalculations: "Автоматични изчисления и баланси",
    instructionExample: "Пример:",
    instructionExampleText: "Ако играч плати 20 лв. вместо 15 лв., оставащите 5 лв. се запазват в неговия баланс за следващи събития.",
    instructionTransparency: "Прозрачност:",
    instructionTransparencyText: "Всички играчи имат достъп до своя баланс и история на плащанията, което гарантира прозрачност.",
    instructionFinalMessage3: "Системата за плащания в SureGo прави финансовото управление лесно, прозрачно и ефективно за всички! 💰⚡",
  },
  en: {
    // Header
    features: "Features",
    howItWorks: "How It Works",
    testimonials: "Testimonials",
    faq: "FAQ",
    
    // Hero
    heroTitle: "Say goodbye to chaos in football meetings!",
    heroSubtitle: "Manage events, players and payments - directly from your phone.",
    
    // Instructions
    instructions: "Instructions",
    
    // Newsletter
    newsletterTitle: "Subscribe for news and features",
    newsletterSubtitle: "Be the first to learn about new features, events and tips for organizing matches.",
    newsletterPlaceholder: "Your email",
    newsletterButton: "Subscribe",
    newsletterDisclaimer: "We will never share your email. You can unsubscribe at any time.",
    
    // Footer
    home: "Home",
    support: "Support",
    help: "Help",
    contact: "Contact",
    legal: "Legal",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    language: "Language",
    allRightsReserved: "All rights reserved.",

    // Features
    featuresTitle: "Features That Make a Difference",
    featuresSubtitle: "SureGo contains everything you need for hassle-free organization of football events",
    feature1Title: "Create Matches and Training Sessions",
    feature1Desc: "Quickly plan and manage football events with all necessary details.",
    feature2Title: "Manage Players with Roles and Positions",
    feature2Desc: "Organize players by positions, skills and special team roles.",
    feature3Title: "Automatic Invites and Notifications",
    feature3Desc: "Automatically send invitations and reminders to players for upcoming matches.",
    feature4Title: "Team Balancing",
    feature4Desc: "Intelligent distribution of players for balanced and competitive teams.",
    feature5Title: "Track Funds and Payments",
    feature5Desc: "Easily track payments and the overall team balance.",
    feature6Title: "Game Statistics and History",
    feature6Desc: "Review statistics for matches, attendance and team performance.",

    // How It Works
    howItWorksTitle: "How Does SureGo Work?",
    howItWorksSubtitle: "Only six easy steps separate you from perfectly organized football events",
    step1Title: "Download the App",
    step1Desc: "Download SureGo from the App Store or Google Play for free.",
    step2Title: "Create an Account",
    step2Desc: "Quick registration with Google, Apple ID or email.",
    step3Title: "Create a Team",
    step3Desc: "Create your team and set up its basic parameters.",
    step4Title: "Add Players",
    step4Desc: "Invite players by phone or SureGo ID to your team.",
    step5Title: "Organize an Event",
    step5Desc: "Set date, time, location and participation conditions.",
    step6Title: "Track Confirmations and Payments",
    step6Desc: "Monitor who has confirmed and paid for participation.",

    // Registration
    registrationTitle: "Account Creation",
    regStep1Title: "Download the App",
    regStep1Desc: "Available on App Store and Google Play",
    regStep2Title: "Choose Registration Method",
    regStep2Desc: "Multiple easy ways to create an account",
    regStep3Title: "Register with Email",
    regStep3Desc: "Enter your details for quick registration",
    regStep4Title: "Activate Your Account",
    regStep4Desc: "Confirm and start using the application",

    // App Showcase
    appShowcaseTitle: "See the App in Action",
    screenshot1Title: "Create Team",
    screenshot2Title: "Invite Players",
    screenshot3Title: "Assign Players",
    screenshot4Title: "Organize and Play!",

    // Testimonials
    testimonialsTitle: "Proven Results",
    testimonialsSubtitle: "Thousands of organizers and football players already rely on SureGo",
    testimonial1: "\"Finally, the excuses stopped – everyone knows when and where we are!\"",
    testimonial1Author: "Kaloyan",
    testimonial1Position: "match organizer in Sofia",
    testimonial2: "\"With SureGo, organizing matches became easy! We no longer have communication problems.\"",
    testimonial2Author: "Martin",
    testimonial2Position: "team captain in Varna",
    eventsOrganized: "events organized",
    activeTeams: "active teams",

    // FAQ
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Answers to the most commonly asked questions about using SureGo",
    faq1Question: "How do I add players?",
    faq1Answer: "You can add players in several ways: by sending an invitation by email or phone, sharing a join code, or searching by SureGo ID. Once a player accepts the invitation, they are automatically added to your team.",
    faq2Question: "Can I change team lineups?",
    faq2Answer: "Yes, you can easily change lineups at any time. Simply go to the event management section, select the match and move players between teams. The system also offers automatic team balancing based on the players' set skills.",
    faq3Question: "How are payments tracked?",
    faq3Answer: "SureGo offers a built-in payment tracking system. You can mark who has paid, send reminders for unpaid fees, and review the overall team balance. Players receive automatic notifications for amounts due and can mark their payments through the app.",
    faq4Question: "Does it work for tournaments?",
    faq4Answer: "Yes, SureGo supports organizing tournaments with multiple teams. You can create a tournament structure, track results, automatically generate schedules, and manage rankings. The tournament functionality is available in the extended plan of the application.",

    // Call to Action
    ctaTitle: "Ready to play without headaches?",
    ctaSubtitle: "Download SureGo now and start organizing football events easily and quickly.",
    downloadApp: "Download SureGo",

    // Instructions Page Translations
    instructionTitle1: "Creating a SureGo Profile - Quick and Easy!",
    instructionDownloadApp: "Download the App",
    instructionAvailableIn: "Available on:",
    instructionChooseRegistration: "Choose Registration Method",
    instructionCanRegisterWith: "You can register via:",
    instructionGoogleAccount: "Google account",
    instructionAppleId: "Apple ID",
    instructionEmailRegistration: "Email (select \"Create Profile\")",
    instructionEmailRegTitle: "If you chose email registration:",
    instructionEnterEmail: "Enter your email and password",
    instructionPressCreateProfile: "Press \"Create Profile\"",
    instructionCheckEmail: "Check your email for confirmation link",
    instructionActivateProfile: "Activate Your Profile",
    instructionOpenEmail: "Open the email and click on the confirmation link",
    instructionReturnToApp: "Return to the app and select \"Email Login\"",
    instructionEnterCredentials: "Enter email and password - and you're done!",
    instructionProfileReady: "You now have an active profile and are ready to start using SureGo!",

    instructionTitle2: "Create Your Team",
    instructionOpenSection: "Open Section",
    instructionOpenTeamsSection: "Open the \"Teams\" section",
    instructionPressPlus: "Press \"+\"",
    instructionPressPlusButton: "Press \"+\" (in the top right corner)",
    instructionFillData: "Fill in Data",
    instructionFillTeamData: "Fill in name, country, city and add a photo",
    instructionSave: "Save",
    instructionPressSave: "Press \"Save\" - and you're done!",
    instructionTeamReady: "You're now ready to organize your matches without headaches!",

    instructionTitle3: "Adding and Configuring Team Players",
    instructionTeamSubtitle: "You already have a created team - let's organize it perfectly!",
    instructionAccessPlayers: "Access to players section:",
    instructionOpenTeams: "Open the \"Teams\" section",
    instructionSelectTeam: "Select your team",
    instructionClickPlayers: "Click on \"Players\"",
    instructionAddNewPlayer: "Adding a new player:",
    instructionChooseMethod: "Choose a convenient method for you:",
    instructionViaSureGoId: "Via SureGo ID (find it in the player's profile)",
    instructionViaPhone: "Via phone number (manual entry)",
    instructionViaContacts: "From phone contacts (automatic connection)",
    instructionPlayerConfig: "Player Configuration",
    instructionSetRole: "Setting role:",
    instructionMainPlayer: "Main",
    instructionMainPlayerDesc: "(priority invitations)",
    instructionReservePlayer: "Reserve",
    instructionReservePlayerDesc: "(invited second)",
    instructionGuestPlayer: "Guest",
    instructionGuestPlayerDesc: "(invited when needed)",
    instructionObserver: "Observer",
    instructionObserverDesc: "(view only)",
    instructionSpecialty: "Specialty (position):",
    instructionGoalkeeper: "Goalkeeper",
    instructionDefender: "Defender",
    instructionMidfielder: "Midfielder",
    instructionAttacker: "Attacker",
    instructionPositionsUsedFor: "Positions are used for:",
    instructionAutoBalance: "Automatic team balancing during matches",
    instructionDetailedStats: "Detailed statistics by position",
    instructionFormationAnalysis: "Analysis of formations used",
    instructionPlayerNotInSureGo: "If the player is not yet in SureGo:",
    instructionSendInvite: "You can send them an invite link via SMS, email or messenger - they will receive a direct link to download the app and register.",
    instructionAdditionalFeatures: "Additional features:",
    instructionEditProfiles: "Edit profiles later",
    instructionChangePositions: "Change positions and roles",
    instructionIndividualStats: "Individual statistics for each player",
    instructionAfterConfig: "After configuring players, you will be able to:",
    instructionAutoSuggestions: "Receive automatic suggestions for optimal lineups",
    instructionTrackPerformance: "Track performance by positions",
    instructionAnalyzeStrengths: "Analyze team strengths and weaknesses",
    instructionFinalMessage1: "The app will help you manage the team professionally by providing all the necessary tools for success! ⚽📊",

    instructionTitle4: "Creating a Football Event in SureGo",
    instructionEventSubtitle: "Organize perfect matches with a few easy steps!",
    instructionStartNewEvent: "Starting a new event:",
    instructionSelectEvents: "From the team screen select \"Events\"",
    instructionBasicInfo: "Basic information:",
    instructionEnterEventInfo: "Enter event name and description",
    instructionAddLocation: "Add location (with option for exact location via \"Map\" button)",
    instructionPressNext: "Press \"Next\"",
    instructionMatchSettings: "Match settings:",
    instructionDateTime: "Date and time:",
    instructionSelectDate: "Select date and start time",
    instructionSetDuration: "Set duration (in minutes)",
    instructionRepeatability: "Repeatability:",
    instructionOneTime: "One-time",
    instructionOneTimeDesc: "(only for this day)",
    instructionWeekly: "Weekly",
    instructionWeeklyDesc: "(automatic repetition)",
    instructionTeamCount: "Number of teams:",
    instructionOneTeam: "1 team",
    instructionOneTeamDesc: "(game against external team)",
    instructionTwoTeams: "2 teams",
    instructionTwoTeamsDesc: "(internal match)",
    instructionPlayers: "Players:",
    instructionSetMinPlayers: "Set minimum number of players",
    instructionPlayerInvites: "Player invitations:",
    instructionTimeIntervals: "Time intervals for invitations:",
    instructionMainPlayers: "Main players",
    instructionMainPlayersDesc: "(first to receive invitation)",
    instructionReservePlayers: "Reserves",
    instructionReservePlayersDesc: "(receive after main players)",
    instructionGuestPlayers: "Guests",
    instructionGuestPlayersDesc: "(receive last)",
    instructionDeadline: "Confirmation deadline:",
    instructionDeadlineDesc: "If not enough players are gathered by this time, the event is automatically cancelled",
    instructionFinanceAndAdditional: "Finance and additional:",
    instructionParticipationPrice: "Participation price:",
    instructionRoundingOption: "Option to round the amount (remainder goes to treasury)",
    instructionFreeOption: "Free option (if desired)",
    instructionFinalization: "Finalization:",
    instructionAddNotes: "Add notes (optional)",
    instructionCompleteWithCreate: "Complete with \"Create Event\"",
    instructionEventReady: "Done!",
    instructionEventActive: "The event is active and invitations have been sent according to the set settings.",
    instructionAdditionalPossibilities: "Additional possibilities:",
    instructionAutoTeamBalance: "Automatic team balancing (if internal match)",
    instructionTrackConfirmations: "Track confirmations in real time",
    instructionEventNotifications: "Notifications for event changes",
    instructionAutoFillPlayers: "Option to automatically fill missing players from reserves",
    instructionFinalMessage2: "The app will notify you of any change in event status and help you organize a perfect match without headaches! ⚽📅",

    instructionTitle5: "Event Payment Management",
    instructionPaymentSubtitle: "Efficient and transparent financial management for every event!",
    instructionPaymentProcess: "Payment registration process:",
    instructionOpenEvent: "Open the desired event by selecting it from upcoming or past events",
    instructionPressDollarButton: "Press the \"$\" button in the top right corner",
    instructionPaymentScreen: "Payment management screen:",
    instructionSeeParticipants: "You see a list of all participants",
    instructionSeeAmount: "At the top, the payment amount is shown (which can be edited)",
    instructionForEachPlayer: "For each player you have the option to:",
    instructionAddExtraAmount: "Add an additional amount (remains in the player's wallet for future events)",
    instructionReduceAmount: "Reduce the amount",
    instructionProcessCompletion: "Process completion:",
    instructionPressRedButton: "Press the red button in the top right corner",
    instructionSeeSummary: "You will see a summary with:",
    instructionEventPrice: "Event price",
    instructionTotalCollected: "Total amount collected",
    instructionTeamTreasury: "Amount for team treasury",
    instructionConfirmYes: "Confirm with \"Yes\"",
    instructionAdditionalInfo: "Additional information:",
    instructionUnpaidPlayers: "If there are players who haven't paid, the system checks:",
    instructionTreasuryCheck: "Whether the team treasury can cover the missing amount",
    instructionInsufficientFunds: "If there are insufficient funds, the process cannot be completed",
    instructionSystemAdvantages: "System advantages:",
    instructionConvenientManagement: "Convenient payment management without the need to return change",
    instructionFullTransparency: "Full financial transparency",
    instructionAutoCalculations: "Automatic calculations and balances",
    instructionExample: "Example:",
    instructionExampleText: "If a player pays 20 BGN instead of 15 BGN, the remaining 5 BGN is saved in their balance for future events.",
    instructionTransparency: "Transparency:",
    instructionTransparencyText: "All players have access to their balance and payment history, which guarantees transparency.",
    instructionFinalMessage3: "The payment system in SureGo makes financial management easy, transparent and efficient for everyone! 💰⚡",
  }
};

export type Language = "bg" | "en";
type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  t: (key: TranslationKeys) => string;
  changeLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("bg");

  const t = (key: TranslationKeys): string => {
    return translations[language]?.[key] || translations.bg[key];
  };

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
